<?php

// ecnu1, ecnul2, tongji1, caida1, shangshida1, fudan1 done, 20131103

// 输出格式
$result = array(
	'ecnu1' => array(
		array(
			'lecUrl' => 'http://webplus.ecnu.edu.cn//s/168/t/227/a/85270/info.jspy',
			'lecTitle' => 'Side Channel-aware Design of Cryptosystems: Novel Analysis and Construction',
			'lecDate' => '2013-11-07',
			'lecTimeStart' => '10:00',
			'lecTimeEnd' => '',
			'lecSpeaker' => 'Dr.-Ing. S. A. Huss',
			'lecAddress' => '闵行校区信息楼133报告厅',
			'lecContent' => '报告人简介：
								Prof. Dr.-Ing. S. A. Huss, Sorin Alexander Huss received the Dipl.-Ing. and Dr.-Ing. degrees in electrical engineering from Technische University München, Munich, Germany, in 1976 and 1982, respectively. He worked in industry from 1982 until 1990 in different positions with AEG Aktiengesellschaft in Ulm, Germany.
								From 1986 to 1990 he headed the CAD/CAE department of the AEG Integrated Circuits Design Center. During his time in industry he initiated and managed several major national and European research projects. Since 1990, he has been a full professor in the Computer Science Department of Technische University Darmstadt, Germany, and also a faculty member of the Electrical Engineering and Information Technology Department of the same university. Dr. Huss was from 2009 until June 2011 one of the founders and directors of the ‘CASED Center for Advanced Security Research Darmstadt’ heading the ’Secure Things’ research group.
								He authored or coauthored two books, many book chapters, and more than 240 reviewed journal and conference papers. He received several international Best Paper, Outstanding Achievement, and Academic Awards.
								His current research interests are in the areas of embedded systems design methodology, reconfigurable HW/SW architectures for IT security applications, and future car-to-car communication systems.
								Prof. S. A. Huss is a member of ACM, IEEE, German Computer Science Association (GI), and German Information Technology Society (ITG).
								Dr. Huss was an initiator of the COSADE International Workshop, the general chair of several international conferences, and serves as a member of many conference program committees and editorial boards.
								Dr. Huss works in addition to his academic duties as a scientific consultant to the European Union, to the German Research Foundation, and to major German as well as to international companies.
								报告主要内容：
								Cryptosystems intended to secure IT applications especially in mobile environments are more and more subjected to various attacks aimed to the extraction of their cryptographic secrets. Side channel analysis (SCA) methods, which exploit the dynamic power consumption of a cryptosystem, form the foundation of one of the most frequently used attack approaches to unveil cryptographic secrets.
								This presentation gives first an introduction to this field to motivate the need of new construction methods, which consider the SCA-awareness of a cryptosystem as an explicit design goal. Then, some new analysis methods, namely Power Amount Analysis and Stochastic Approach, are discussed as efficient means for a fast and accurate assessment of the SCA resistance of and for the location of information leakage within a cryptosystem. In the third part of the presentation novel construction concepts based on dynamically mutating processing units and on virtualization methods in multi-core HW modules of the underlying embedded system are introduced and discussed in the context of both symmetric and asymmetric encryption schemes. The talk concludes with an outlook on the ongoing own research work aiming to a complete synthesis tool set for an automated construction of SCA-aware cryptographic modules.?',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '闵行校区',
			'tags' => array(),
			'expired' => false,
		),
		array(
			'lecUrl' => 'http://webplus.ecnu.edu.cn//s/168/t/227/a/85714/info.jspy',
			'lecTitle' => '大脑的动态网络：信息理论给我们的启示及其重要意义',
			'lecDate' => '2013-11-07',
			'lecTimeStart' => '15:00',
			'lecTimeEnd' => '',
			'lecSpeaker' => 'Daniele Marinazzo',
			'lecAddress' => '中北校区理科大楼A510报告厅',
			'lecContent' => '报告人简介：
								Daniele Marinazzo，于2007年获得物理学博士。目前在比利时根特大学数据分析学院任副教授。他率领的研究团队主要致力于神经科学研究的方法论和计算方面的研究。作为一名物理学家，他的研究多是跨学科的，常与临床及实验神经科学家合作。他的课题组拥有多个富有成果的合作性课题，包括高级数据分析，多与世界各地的理论与实验课题组共同进行。他经常组织连通方法及其应用相关的研讨会、会议以及杂志专刊。',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
		array(
			'lecUrl' => 'http://webplus.ecnu.edu.cn//s/168/t/227/a/85268/info.jspy',
			'lecTitle' => 'Microsystems and Nanoelectronics, New challenges in a changing industry（信息与材料系列学术报告）',
			'lecDate' => '2013-11-06',
			'lecTimeStart' => '13:00',
			'lecTimeEnd' => '',
			'lecSpeaker' => '马文秀',
			'lecAddress' => '闵行校区信息楼629报告厅',
			'lecContent' => '报告人简介：
								马文秀教授毕业于中国科技大学，1990年获中科院数学博士学位，1994—1996年在德国作汉堡学者，曾任英国Manchestr大学、法国Montpelier大学、加拿大British Columbia大学、美国Minnesota大学等的访问学者，97—2001年任香港城市大学教授，现任美国南佛罗里达大学数学系教授。主要从事孤立子理论、可积系统、正交多项式、符号计算等方面的研究工作，特别在孤立子理论与可积系统方面有很深的学术造诣，在国内外著名杂志上发表学术论文130多篇，编辑专著两部，并组织多次国际学术会。',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
		array(
			'lecUrl' => 'http://webplus.ecnu.edu.cn//s/168/t/227/a/85704/info.jspy',
			'lecTitle' => 'Evolution of Glucose Uptake by Vertebrate Liver Cells',
			'lecDate' => '2013-11-05',
			'lecTimeStart' => '15:00',
			'lecTimeEnd' => '',
			'lecSpeaker' => 'David M. Irwin',
			'lecAddress' => '中北校区理科大楼A1608报告厅',
			'lecContent' => '报告人简介：
								David M. Irwin is a Professor in the Department of Laboratory Medicine and Pathobiology, University of Toronto, Toronto,  OntarioM5G 1L5,  Canada from July 2006. Professor Irwin obtained his degrees at the University of Guelph (B.Sc.) and the University of British Columbia (Ph.D.). He received his postdoctoral training at the Division of Biochemistry and Molecular Biology, University of California, Berkeley. His academic career started at Department of Clinical Biochemistry, University of Toronto (Assist, 1991-1997), followed by the Department of Laboratory Medicine and Pathobiology, from Assistant Professor to Associate Professor of the Department of Laboratory Medicine and Pathobiology (1997-2006). He is also a principal investigator at the Banting and Best Diabetes Centre, University of Toronto, and a scientist at the Toronto General Hospital Research Institute. ',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
		array(
			'lecUrl' => 'http://webplus.ecnu.edu.cn//s/168/t/227/a/85266/info.jspy',
			'lecTitle' => 'Microsystems and Nanoelectronics, New challenges in a changing industry（信息与材料系列学术报告）',
			'lecDate' => '2013-11-05',
			'lecTimeStart' => '14:00',
			'lecTimeEnd' => '',
			'lecSpeaker' => 'Kees Beenakker',
			'lecAddress' => '闵行校区信息楼133报告厅',
			'lecContent' => '报告人简介：
								Kees Beenakker was born in Leiden in 1948. After the gymnasium he studied chemistry and physics at Leiden university. In 1974 he joined Philips Research Laboratories in Eindhoven. There he was involved in various research projects related to IC technology. In 1982 he moved to the Philips Semiconductor Division in Nijmegen to become head of the corporate assembly process and equipment development. In 1987 he resigned at Philips and became cofounder of Eurasem, a European hi-rel IC assembly company. In 1989 Kees Beenakker joined Dimes and is since 1990 full professor at the faculty of EEMCS (Electrical Engineering, Mathematics and Computer Science) of Delft University of Technology. From 1999 till 2009 he was chairman of the department of Microelectronics and Computer Engineering. In 2006 he was appointed guest professor at TsinghuaUniversity and in 2012 at the Institute of Semiconductors of CAS. He is a member of the Dutch International Innovation advisory board. Since 2012 he is managing director of the TU Delft-Beijing Research Centre in Beijing.',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
		array(
			'lecUrl' => 'http://webplus.ecnu.edu.cn//s/168/t/227/a/86099/info.jspy',
			'lecTitle' => '无机细胞化学：从生物活性到亚细胞检测（清松化学学术系列讲座）',
			'lecDate' => '2013-11-04',
			'lecTimeStart' => '13:30',
			'lecTimeEnd' => '',
			'lecSpeaker' => 'Clotilde Policar',
			'lecAddress' => '闵行校区化学楼135报告厅',
			'lecContent' => '报告人简介：
								Prof. Clotilde Policar，1992-1995巴黎五大博士（博士论文获国家奖学金）1996-2008巴黎十一大助理教授 2005荣获特许任教资格 2008巴黎高师教授 2010华东师范大学中法班授课欧洲科学基金委员会评定成员；ANR先进应用评定成员；CEFIPRA法国-印度先进工作评定；AXA法国政府先进科技成果评定委员会成员；法国实验室评估 (AERES, CNRS)；(2010-14)??金属蛋白与模型?科研组主席。
								报告内容简介：
								1）SOD类似物是可以使超氧化物歧化酶活性再生的小分子络合物，这些超分子蛋白通过催化性的歧化超氧化阴离子从而保护细胞免受氧化应激，在细胞层面测试它们的抗氧化活性非常重要，一些最近的氧化应激的细胞模型将被呈现。
								2）我们将介绍一些金属-CO衍生物用作亚细胞成像方面的IR探针，在这过程中使用了最前沿的偶联技术，AFM，IR镭射器(AFMIR)[3]以及基于FTIR的同步加速器.有趣的是，金属-CO衍生物还可以用作荧光研究，例如基于简单分子核心的双模型探针。我们还发现IR模式和荧光模式相互之间是连续的，这证明了目前的SCoMPI在双模型成像方面的可行性。',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
		array(
			'lecUrl' => 'http://webplus.ecnu.edu.cn//s/168/t/227/a/85693/info.jspy',
			'lecTitle' => '莎士比亚与中国文学——从纸面到台面的忠实与背叛（大夏讲坛132讲）',
			'lecDate' => '2013-11-04',
			'lecTimeStart' => '13:00',
			'lecTimeEnd' => '',
			'lecSpeaker' => '彭镜禧',
			'lecAddress' => '闵行校区中文系4楼报告厅',
			'lecContent' => '主讲人简介：
								彭镜禧教授是台湾新竹县人，台湾大学外文系硕士、密西根大学比较文学博士。先后在耶鲁大学、牛津大学、芝加哥大学研修莎学，曾任《中外文学》主编、台湾比较文学学会会长、Taipei Chinese PEN Quaterly主编、台大外国语文学系主任、戏剧学系主任、文学院院长等。
								彭镜禧教授曾牵头成立“台大莎士比亚论坛”（NTU Shakespeare Forum)，建立台湾莎士比亚研究资料库，为台湾莎学与世界莎学的接轨打下了坚实的基础。
								彭镜禧教授专攻中西戏剧、莎士比亚、文学翻译，并致力于英诗阅读的推广。已出版编、著、译作品三十余种，具有广泛学术影响。
								近年，彭镜禧教授与台湾豫剧团合作，在莎士比亚戏剧的跨文化改编领域成绩卓著。2012年与台湾师范大学陈芳教授合作改编自莎剧的《量?度》（Measure for Measure），自演出以来广受好评。2009年与2011年，彭镜禧教授曾得到“英国莎士比亚学会”与“美国莎士比亚学会”的邀约，根据他改编演出的《约/束》、《威尼斯商人》也得到西方莎学界的肯定。
								报告内容概要：
								莎士比亚是诗人也是剧作家。四百多年来他的作品传诵世界各地，影响既深且广，一般人都希望品尝到“原汁原味”的莎士比亚。然而这是一种必须打破的迷思，即使莎士比亚在世的时候也没有“原作”，跨越时空的演出都是“跨文化”行为。当今的英语世界，都不可能演出莎士比亚的原貌，更别说跨越文化疆域更大的其他语言、剧种的改编。
								 “背叛”原作必然且必要。从《威尼斯商人》和《量?度》的几种英语、中文的翻译、演出、改编中可以看出，戏剧从书面到台面的展现，要靠导演、演员、设计群等共同完成。翻译者、改编者、读者群等对文本的诠释都是背叛式的。不妨说，参与莎士比亚戏剧演出的，从译者、编者到演出团队，乃至观众，都是莎士比亚的同工——也是他的分身。表面的背叛极可能是对莎士比亚以及艺术本身的忠实。',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
		array(
			'lecUrl' => 'http://webplus.ecnu.edu.cn//s/168/t/227/a/85695/info.jspy',
			'lecTitle' => '包世臣与十九世纪早期中国的农业改革（大夏讲坛131讲）',
			'lecDate' => '2013-11-04',
			'lecTimeStart' => '10:00',
			'lecTimeEnd' => '',
			'lecSpeaker' => '罗威廉',
			'lecAddress' => '闵行校区图书馆报告厅',
			'lecContent' => '主讲人简介：
								罗威廉（William T.Rowe），美国霍普金斯大学历史系讲座教授，约翰?霍普金斯大学东亚研究项目主任。
								罗威廉教授被誉为“美国新一代中国研究最有影响的历史学家之一”,他1980年代在斯坦福大学出版社出版的关于清代汉口的两本著作《汉口：一个中国城市的商业和社会》和《汉口：一个中国城市中的冲突和社区》被国际学术界普遍认为是中国城市史研究的经典著作，挑战了过去占统治地位的马克斯·韦伯关于中国城市缺乏社会共同体的论断。其中第二本由于使用了“公共领域”（public sphere）的概念，在西方学术界引起了关于近代中国公共领域发展的大讨论，本书还获得了城市史学会的最佳著作奖。以上两本书都早有中译本在大陆问世，影响很大。他的著作还包括斯坦福大学出版社出版的《拯救世界：陈宏谋与18世纪中国的精英意识》和《七个世纪的血雨：一个中国城市里的暴力》，哈佛大学出版社出版的《中国的大清帝国》。他长期在美国霍普金斯大学历史系任教，并曾经担任系主任，培养了大批中国史研究的人才，他也是国际上许多重要学术杂志的编委，在一些国际专业学会中担任各种重要角色。报告内容概要：
								包世臣(1775-1855)在军事、外交、盐的专卖、粮食进贡等方面提出了一系列的重大改革措施，其思想在19世纪产生过深远影响，他还在农村生活和农业改革方面提出了非常有见地的看法，这是本次学术讲座的重点。他与同时代的洪亮吉形成鲜明对比，洪认为帝国面临人口和资源危机，但是包世臣指出提高农业产量还有极大的空间，例如农作物的种植选择、农业劳动力的调配、农业商品化、地方社会组织等等，由此改进人们的生计。较之洪亮吉，包更经常使用统计分析的方法去支持其观点。面对内外交困的局势，怎样国富民强成为一个要回答的根本问题，包世臣对此非常乐观，认为这是一个可以达到的目标，并同时可以缓和当时已经普遍出现的社会危机。以史为鉴，这个讲座对于我们今天所面临的问题有很大的启发意义',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
	),
	'ecnu2' => array(		
	),
	'tongji1' => array(
		array(
			'lecUrl' => 'http://news.tongji.edu.cn/classid-21-newsid-40553-t-show.html',
			'lecTitle' => '德意志审美现代性话语的文化生态要素 ',
			'lecDate' => '2013-11-04',
			'lecTimeStart' => '13:30',
			'lecTimeEnd' => '15:00',
			'lecSpeaker' => '张政文 教授（黑龙江大学校长、博导）',
			'lecAddress' => '外国语学院同文楼二楼报告厅（214室）',
			'lecContent' => '',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
		array(
			'lecUrl' => 'http://news.tongji.edu.cn/classid-21-newsid-40759-t-show.html',
			'lecTitle' => '1: New Trends in Vibration Based Structural Health Monitoring & 2: Importance of Wave Propagation in the Soil for the Prediction of Railway induced Vibration',
			'lecDate' => '2013-11-08',
			'lecTimeStart' => '9:00',
			'lecTimeEnd' => '10:30',
			'lecSpeaker' => '比利时鲁汶大学Prof. Guido De Roeck和Prof. Geert Degrande',
			'lecAddress' => '土木大楼 A305',
			'lecContent' => '',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
		array(
			'lecUrl' => 'http://news.tongji.edu.cn/classid-21-newsid-40713-t-show.html',
			'lecTitle' => '德意志福利国家——历史基础和当下问题（德语）',
			'lecDate' => '2013-11-06',
			'lecTimeStart' => '18:30',
			'lecTimeEnd' => '',
			'lecSpeaker' => 'Prof. Dr. Gerhard Albert Ritter（牛津大学圣安东学院研究员、柏林洪堡大学哲学院名誉博士、“德意志联邦十字勋章”获得者）',
			'lecAddress' => '中德学院901室（赤峰路50号）',
			'lecContent' => '',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
	),
	'caida1' => array(
		array(
			'lecUrl' => 'http://ky.shufe.edu.cn/structure/kyc/xshdnr_138826_1.htm',
			'lecTitle' => '当前宏观经济金融形势',
			'lecDate' => '2013-11-08',
			'lecTimeStart' => '14:00',
			'lecTimeEnd' => '16:00',
			'lecSpeaker' => '国务院发展研究中心金融研究所 张承惠研究员',
			'lecAddress' => '369校区大礼堂',
			'lecContent' => '',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
		array(
			'lecUrl' => 'http://ky.shufe.edu.cn/structure/kyc/xshdnr_138822_1.htm',
			'lecTitle' => '守正出新——传统小说研究思路和方法再议',
			'lecDate' => '2013-11-06',
			'lecTimeStart' => '16:00',
			'lecTimeEnd' => '18:00',
			'lecSpeaker' => '中国社会科学院 竺青教授',
			'lecAddress' => '同新楼201室',
			'lecContent' => '',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
	),
	'shangshida1' => array(
		array(
			'lecUrl' => 'http://xcb.shnu.edu.cn/Default.aspx?tabid=2200&ctl=Details&mid=1724&ItemID=119173&SkinSrc=[L]Skins/xuanchuan1/xuanchuan1',
			'lecTitle' => '《回眸中世纪》中世纪哲学中的神与人',
			'lecDate' => '2013-11-25',
			'lecTimeStart' => '',
			'lecTimeEnd' => '13:30',
			'lecSpeaker' => '上海师范大学徐善伟教授',
			'lecAddress' => '文苑楼708室',
			'lecContent' => '',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
		array(
			'lecUrl' => 'http://xcb.shnu.edu.cn/Default.aspx?tabid=2200&ctl=Details&mid=1724&ItemID=118179&SkinSrc=[L]Skins/xuanchuan1/xuanchuan1',
			'lecTitle' => 'Web of Science（SCI\SSCI\A&HCI）数据库在科研中的价值与应用',
			'lecDate' => '2013-11-05',
			'lecTimeStart' => '18:30',
			'lecTimeEnd' => '20:00',
			'lecSpeaker' => '数据库培训师',
			'lecAddress' => '徐汇校区东部文苑楼电子阅览室',
			'lecContent' => '介绍如何利用Web of Science进行选题，如何利用Web of Science发现研究课题的发展脉络并判断未来发展方向以及快速查找跟自己从事的研究最相关的科技文献，如何发现研究热点、跟踪学术领军人物开展科研，如何跟踪国际上最新的研究动态，如何选择合适的期刊进行投稿，快速准确地按照期刊要求的格式生成文中、文后的参考文献，减少因为格式问题导致的退稿。',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
		array(
			'lecUrl' => 'http://xcb.shnu.edu.cn/Default.aspx?tabid=2200&ctl=Details&mid=1724&ItemID=118179&SkinSrc=[L]Skins/xuanchuan1/xuanchuan1',
			'lecTitle' => '查找与使用国内外硕博士学位论文',
			'lecDate' => '2013-11-12',
			'lecTimeStart' => '18:30',
			'lecTimeEnd' => '20:00',
			'lecSpeaker' => '马凌云',
			'lecAddress' => '徐汇校区东部文苑楼电子阅览室',
			'lecContent' => '学位论文是撰写论文过程中非常重要的文献资源，本讲座介绍国内外多个硕、博士学位论文数据库的特色及检索方法，并介绍学位论文原文获取途径。',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
		array(
			'lecUrl' => 'http://xcb.shnu.edu.cn/Default.aspx?tabid=2200&ctl=Details&mid=1724&ItemID=118179&SkinSrc=[L]Skins/xuanchuan1/xuanchuan1',
			'lecTitle' => '基于数字化环境下的古文献检索与利用',
			'lecDate' => '2013-11-19',
			'lecTimeStart' => '18:30',
			'lecTimeEnd' => '20:00',
			'lecSpeaker' => '赵龙',
			'lecAddress' => '徐汇校区东部文苑楼电子阅览室',
			'lecContent' => '以馆藏古籍数据库为基础，结合网络开放资源，介绍古文献数字资源的利用及注意事项。',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
		array(
			'lecUrl' => 'http://xcb.shnu.edu.cn/Default.aspx?tabid=2200&ctl=Details&mid=1724&ItemID=118179&SkinSrc=[L]Skins/xuanchuan1/xuanchuan1',
			'lecTitle' => '外文数据库的检索与利用（综合数据库）',
			'lecDate' => '2013-11-26',
			'lecTimeStart' => '18:30',
			'lecTimeEnd' => '20:00',
			'lecSpeaker' => '刘晓霞',
			'lecAddress' => '徐汇校区东部文苑楼电子阅览室',
			'lecContent' => '介绍我馆订购的外文综合性数字资源，包括EBSCO、Elsevier、牛津等期刊库，重点介绍EBSCO、Elsevier等数据库的检索方法和使用技巧。',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
		array(
			'lecUrl' => 'http://xcb.shnu.edu.cn/Default.aspx?tabid=2200&ctl=Details&mid=1724&ItemID=119172&SkinSrc=[L]Skins/xuanchuan1/xuanchuan1',
			'lecTitle' => '《回眸中世纪》中世纪文学中的神与情',
			'lecDate' => '2013-11-18',
			'lecTimeStart' => '13:30',
			'lecTimeEnd' => '',
			'lecSpeaker' => '上海外国语大学教授张世华',
			'lecAddress' => '文苑楼708室',
			'lecContent' => '18世纪回眸中世纪孕育出浪漫主义；21世纪回眸中世纪将启导什么？第三讲 中世纪文学中的神与情',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
		array(
			'lecUrl' => 'http://xcb.shnu.edu.cn/Default.aspx?tabid=2200&ctl=Details&mid=1724&ItemID=119166&SkinSrc=[L]Skins/xuanchuan1/xuanchuan1',
			'lecTitle' => '《回眸中世纪》中世纪的民族',
			'lecDate' => '2013-11-11',
			'lecTimeStart' => '13:30',
			'lecTimeEnd' => '',
			'lecSpeaker' => '华东师范大学沈坚教授',
			'lecAddress' => '文苑楼708室',
			'lecContent' => '18世纪回眸中世纪孕育出浪漫主义；21世纪回眸中世纪将启导什么？第二讲：中世纪的民族',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
	),
	'fudan1' => array(
		array(
			'lecUrl' => 'http://stu.fudan.edu.cn/event/main.html?108',
			'lecTitle' => '《资本论》与当代世界 第五讲',
			'lecDate' => '2013-11-04',
			'lecTimeStart' => '15:30',
			'lecTimeEnd' => '17:30',
			'lecSpeaker' => '雅克·比岱教授',
			'lecAddress' => '光华楼西主楼2604',
			'lecContent' => '雅克·比岱（Jacques Bidet），法国哲学家和社会理论家，西巴黎大学（原巴黎第十大学）荣休教授，《今日马克思》杂志荣誉主编，“世界马克思大会”主席。代表作为《如何理解<资本论>？》（Que faire du Capital?）（1985），《现代性理论》（Théorie de la modernité）（1990），《一般理论》（Théorie générale）（1999），《对于<资本论>的探讨与重建》（Explication et reconstruction du Capital）（2004），《世界-国家：全球范围内的自由主义、社会主义和共产主义》（L’état-monde, Libéralisme, Socialisme et Communisme à l\'échelle mondiale, Refondation du marxisme）（2011）',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
		array(
			'lecUrl' => 'http://stu.fudan.edu.cn/event/main.html?145',
			'lecTitle' => '云南的形成（公元前二世纪到公元二十世纪）',
			'lecDate' => '2013-11-04',
			'lecTimeStart' => '18:30',
			'lecTimeEnd' => '20:00',
			'lecSpeaker' => '杨斌副教授',
			'lecAddress' => '光华楼西主楼2801',
			'lecContent' => '云南融入中国的过程，不仅仅是中国历史进程中的问题，而是一个跨地区、跨文化的进程。报告从云南的形成过程来管窥中国的形成这个大命题，并以南方丝绸之路来阐述云南和周围区域的多元联系，从军事征服、行政管辖、移民和文化交流、云南人的形成、经济转型以及1950-80年代的民族识别等多个方面，阐述云南的形成过程，也就是云南融入中国的过程。',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
	),
	'format' => array(
		array(
			'lecUrl' => '',
			'lecTitle' => '',
			'lecDate' => '',
			'lecTimeStart' => '',
			'lecTimeEnd' => '',
			'lecSpeaker' => '',
			'lecAddress' => '',
			'lecContent' => '',
			'longitude' => '',
			'latitude' => '',
			'subSchool' => '',
			'tags' => array(),
			'expired' => false,
		),
	),
);

header('Content-Type: application/json');  
echo json_encode($result);